name: Build FlyEnv macOS Packages (No Sign)
on:
  push:
    paths:
      - 'build/macos.build.yml'

jobs:
  build-macos:
    name: Build (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: x64
            os: macos-15-intel # Intel 架构云端环境
            target: x64
          - arch: arm64
            os: macos-latest # Apple Silicon 架构云端环境
            target: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/helper-go/go.mod'
          cache-dependency-path: 'src/helper-go/go.sum'

      - name: Cache node_modules and node-gyp
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            **/node_modules
            .yarn/cache
            ~/.cache/node-gyp
          key: ${{ runner.os }}-${{ matrix.arch }}-node-${{ hashFiles('**/package.json') }}

      - name: Install Yarn and build tools
        run: |
          npm install -g yarn node-gyp

      - name: Install dependencies
        run: yarn install

      - name: Build Go helper
        run: |
          cd "$GITHUB_WORKSPACE/src/helper-go"
          chmod +x ./build.sh
          bash ./build.sh

      - name: Build Electron App
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 核心修改：通过环境变量强行关闭 electron-builder 的代码签名
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
        run: yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FlyEnv-macOS-${{ matrix.arch }}
          path: |
            release/*.dmg
